### ISSUE TITLE
Temperature sensors

### ISSUE THREAD

**Issue by Miggas** [SasaKaranovic/OpenFanController#1]
Would it be possible to implement the ability to use temperature sensors?, I'm currently using 2, and this would be useful to make a Fan/Pump curve to the water temperature instead of the CPU/GPU temps.
I'm also planning on sharing the design, as I'm building a Big Corsair Fan HUB to control both Fan speeds and their RGB using https://github.com/Legion2/CorsairLightingProtocol

**Comment by Miggas** [comment]
Also would it be possible to implement the ability to use temperature sensors?, I'm currently using 2, and this would be useful to make a Fan/Pump curve to the water temperature instead of the CPU/GPU temps

**Comment by SasaKaranovic** [comment]
Hey @Miggas 

Yes it would be fairly easy to add support for one or more temperature sensors.
Are you using them with OpenFAN board? How many sensors do you have and what type/pn?

**Comment by Miggas** [comment]
Temperature probe type: NTC, 10KΩ at 25°C
They are the most common type of temp probe used in water cooling loops.

**Comment by SasaKaranovic** [comment]
Currently OpenFAN does not support analogue sensors, only digital ones (I2C or 1-Wire).
But maybe in the next revision we can add support for analogue/NTC sensors.

**Comment by lietu** [comment]
Why is this closed? I don't see any support for NTC thermal probes which are incredibly standard in the PC world.

**Comment by laleeroy** [comment]
Any updates to this? Would love to see this
