### ISSUE TITLE
Fan alias feature

### ISSUE THREAD

**Issue by Th3M1k3y** [SasaKaranovic/OpenFanController#12]
It would be nice to have the ability to rename fans in the UI.

Maybe something like Alias <sub>(FAN #1)</sub>

Control through the API remain as it is currently.

**Comment by SasaKaranovic** [comment]
Thanks for the suggestion! I like this idea.

**Comment by lord-xeon** [comment]
I also would like this feature.  I started to build something to keep track of the same for me.  While it's probably not a problem for everyone, it's nice to know `Fan 6` is the one on the top of the case.

**Comment by SasaKaranovic** [comment]
@Th3M1k3y @lord-xeon 

I have just created a new branch https://github.com/SasaKaranovic/OpenFanController/tree/sk_general_improvements that contains API paths that allow setting of fan alias (name).

The UI is also updated to show aliases (if set).
To set an alias, you would double-click on the fan name and the pop-up will appear asking for new fan name.

If you have the chance, please give it a try and let me know if you have any suggestions.
I will take couple of days to test and make sure there are no issues or regressions and then if everything looks alright merge it into master.

**Comment by Th3M1k3y** [comment]
I am running the controller in the unraid docker, not sure how to go about testing this.

**Comment by SasaKaranovic** [comment]
>  I am running the controller in the unraid docker, not sure how to go about testing this.

You would have to run it manually or build a new docker image.
It's ok if it's not convenient for you, I will release a new docker image once it's tested and then you can just update your container.

**Comment by SasaKaranovic** [comment]
![image](https://github.com/SasaKaranovic/OpenFanController/assets/75916/7de16ec1-c509-4f3c-a492-06f6d538a4f4)

This feature should be live now in the release branch.
If you update (force-update) your docker image, you should have this option.
Double-click on the fan name will show a prompt to enter a new fan name.

Let me know how it works and if you encounter any issues.
