### ISSUE TITLE
Update enclosure height to fit latest batch of board

### ISSUE THREAD

**Issue by Th3M1k3y** [SasaKaranovic/OpenFanController#15]
A capacitor is too tall, so the lid can't be closed.

I added a hole so the capacitor could go through. With this the surface of the capacitor sits 0.1mm under the surface of the lid.

![2024-06-02 10 52 49](https://github.com/SasaKaranovic/OpenFanController/assets/29869794/1ae20a37-68df-4bc6-95af-410b429b156d)

**Comment by SasaKaranovic** [comment]
Thank you @Th3M1k3y !

I have been informed that the PCB shop used a slightly taller capacitor in this batch.
As the result it is colliding with the enclosure.
I will update the enclosure design to make it taller so it fits the board nicely.

**Comment by SasaKaranovic** [comment]
@Th3M1k3y 
I have just updated the enclosure by increasing the height by 2mm.
If you want you can print the new enclosure and give it a try.
If it works well for you too, let me know and we can close this issue.
