### ISSUE TITLE
Leaking all user IPs to an external service

### ISSUE THREAD

**Issue by lietu** [SasaKaranovic/OpenFanController#21]
https://github.com/SasaKaranovic/OpenFanController/blob/1ab7c3a358990d5f561d514d52a965879bd951a3/Software/Python/webpage/index.html#L20

You are using a random external service for fetching fonts, this means anyone using your software has their IP address sent to this 3rd party service, and the host can choose to log the traffic however they wish. This has gotten a lot of people already in trouble with the EU GDPR.

If for some reason having `Inter` is very important, then bundle it: https://fontsource.org/fonts/inter

**Comment by SasaKaranovic** [comment]
Thank you @lietu !
The font file is not being served locally which should resolve this issue.
