### ISSUE TITLE
zero rpm showing

### ISSUE THREAD

**Issue by russellevans** [SasaKaranovic/OpenFanController#23]
I have purchased the openfan controller from you (Order #1085)....I live in the UK and with shipping costs it was expensive but I was happy if it did the job.

When I plug the fans in they turn for a moment and stop
There is two header where a fan runs but non of the others make the fans turn.
(These are 4 wire fans but if I only plug in three wires the fan does run)

I was seeing RPM on the self hosted web page but now everything shows as zero

I am using noctua NF-A14 & NF-A12x25 fans
The host is a Pi 4 and locally built the docker image to get things to work

My guess is I have a bad board
(Maybe I could of damaged it but that does not explain why only two headers ran fans out of the box)

The container logs seem clean but I am not an expert

What do you recommend to do next?  Will you send a replacement board?

`Sep 18 2024 06:19:43.349 pid:7 FanCommander.py          103 DEBUG 	SN: DE615CB147712230
Sep 18 2024 06:19:43.349 pid:7 FanCommander.py          104 DEBUG 	VID:11914 PID:10
Sep 18 2024 06:19:43.349 pid:7 FanCommander.py          105 DEBUG 	Location: 1-1.4:1.0
Sep 18 2024 06:19:43.349 pid:7 FanCommander.py          106 DEBUG 	Interface: Board CDC
Sep 18 2024 06:19:43.349 pid:7 FanCommander.py          108 DEBUG Using 'OpenFan - Board CDC' as Fan Controller COM port
Sep 18 2024 06:19:43.349 pid:7 webserver.py             302 INFO  Using COM port `/dev/ttyACM0 - OpenFan - Board CDC` (Found through USB VID:PID).
Sep 18 2024 06:19:43.349 pid:7 webserver.py             304 INFO  Fan Controller port: /dev/ttyACM0 - OpenFan - Board CDC
Sep 18 2024 06:19:43.352 pid:7 serial_driver.py          43 DEBUG Serial driver initialized with
Sep 18 2024 06:19:43.352 pid:7 serial_driver.py          44 DEBUG -- flush_on_write: 'True'
Sep 18 2024 06:19:43.352 pid:7 serial_driver.py          45 DEBUG -- timeout: '2'
Sep 18 2024 06:19:43.352 pid:7 webserver.py             334 INFO  Karanovic Research OpenFan - Starting API server
Sep 18 2024 06:19:43.357 pid:7 webserver.py             339 INFO  Listening on port 3000
Sep 18 2024 06:18:09.763 pid:7 webserver.py             145 INFO  Request:STATUS
Sep 18 2024 06:18:09.763 pid:7 FanCommander.py           24 DEBUG CMD:0 Data: None
Sep 18 2024 06:18:09.763 pid:7 FanCommander.py           25 DEBUG Sending `>00`
Sep 18 2024 06:18:09.809 pid:7 FanCommander.py           31 DEBUG [0001131594][I][HCOMM] >00
Sep 18 2024 06:18:09.809 pid:7 FanCommander.py           31 DEBUG [0001131594][D][HCOMM] host_comm_tick: Start character found (Len=2)
Sep 18 2024 06:18:09.809 pid:7 FanCommander.py           31 DEBUG [0001131594][D][HCOMM] host_comm_parse_package
Sep 18 2024 06:18:09.809 pid:7 FanCommander.py           31 DEBUG [0001131594][D][HCOMM] A=00 H:0x00
Sep 18 2024 06:18:09.809 pid:7 FanCommander.py           31 DEBUG [0001131594][D][HCOMM] CMD_FAN_ALL_GET_RPM
Sep 18 2024 06:18:09.809 pid:7 FanCommander.py           31 DEBUG <00|00:0000;01:0000;02:0000;03:0000;04:0000;05:0000;06:0000;07:0000;08:0000;09:0000;
Sep 18 2024 06:18:09.810 pid:7 FanCommander.py           33 DEBUG Response: '<00|00:0000;01:0000;02:0000;03:0000;04:0000;05:0000;06:0000;07:0000;08:0000;09:0000;'
Sep 18 2024 06:18:09.810 pid:7 FanCommander.py           46 DEBUG {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0}`

**Comment by SasaKaranovic** [comment]
Hey @russellevans 

Sorry about late reply. Please send an email to shop@sasakaranovic.com and we will resolve this issue ASAP.
GitHub issues are more for community contributions/discussions etc.

Also I understand and agree that shipping prices are high. Unfortunately, at the moment those are the "best" rates I can get with the current shipping company...
I am a single person sending a few packets a month, so understandably they are not going to fight for a drop in a bucket.
And to be honest, I don't want to "mislead" people by spiking up the prices and claiming that shipping is "free", because then if you buy multiple items, you pay that inflated (shipping) price multiple times...
