### ISSUE TITLE
Update firmware on GitHub

### ISSUE THREAD

**Issue by GewoonJaap** [SasaKaranovic/OpenFanController#25]
A few weeks ago we chatted via e-mail about the new firmware for the latest revision of the openFAN boards. Could you also upload this firmware here on GitHub, so all the other users won't install out-dated firmware ;)

**Comment by SasaKaranovic** [comment]
Thanks @GewoonJaap !
The firmware you received is not newer, it's the exact same, just modified for the revision of the board you received. :)
