### ISSUE TITLE
Alert pin in FW

### ISSUE THREAD

**Issue by ledadrian** [SasaKaranovic/OpenFanController#27]
I wanted to try this with a Seeed Studio XIAO RP2040, but I noticed the EMC2305 has alert pins connected to GPIO 11 and GPIO 17. I was looking at the FW to change the pins becuase the seeed studio board does not breakout those pins. I was unable to find those pins being used in the FW. Are the alerts being used in this version?

**Comment by SasaKaranovic** [comment]
You can program the EMC2305 to create alerts for various conditions.
This feature is not used right now.
