### ISSUE TITLE
USB CDC serial stops working

### ISSUE THREAD

**Issue by MRezaNasirloo** [SasaKaranovic/OpenFanController#4]
I don't have the board, but I installed the firmware on an RP2040 board to confirm a bug that I had with the TinyUSB library. When the host Windows PC wakes up from sleep, the USB CDC does not respond anymore. It only starts functioning after a USB replug or restart. This might be related to this issue: https://github.com/hathach/tinyusb/issues/1416.

Could you confirm if you have been able to reproduce this issue?

Thank you.

**Comment by SasaKaranovic** [comment]
Hi @MRezaNasirloo!
I have not been able to reproduce this and I believe it should not affect OpenFAN since it is SATA powered, not USB powered.
